package org.com.myapp.model;

// Generated Dec 4, 2014 12:47:13 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Diarypermission generated by hbm2java
 */
@Entity
@Table(name = "diarypermission", catalog = "diary_v2")
public class DiaryPermission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDiaryPermission;
	private UserProfile userprofile;
	private Diary diary;
	private boolean isAllowed;

	public DiaryPermission() {
	}

	public DiaryPermission(UserProfile userprofile, Diary diary,
			boolean isAllowed) {
		this.userprofile = userprofile;
		this.diary = diary;
		this.isAllowed = isAllowed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDiaryPermission", unique = true, nullable = false)
	public Integer getIdDiaryPermission() {
		return this.idDiaryPermission;
	}

	public void setIdDiaryPermission(Integer idDiaryPermission) {
		this.idDiaryPermission = idDiaryPermission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InvitedUserId", nullable = false)
	public UserProfile getUserprofile() {
		return this.userprofile;
	}

	public void setUserprofile(UserProfile userprofile) {
		this.userprofile = userprofile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DiaryId", nullable = false)
	public Diary getDiary() {
		return this.diary;
	}

	public void setDiary(Diary diary) {
		this.diary = diary;
	}

	@Column(name = "IsAllowed", nullable = false)
	public boolean isIsAllowed() {
		return this.isAllowed;
	}

	public void setIsAllowed(boolean isAllowed) {
		this.isAllowed = isAllowed;
	}

}
