package org.com.myapp.model;
// Generated Dec 4, 2014 12:47:13 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendrequestId generated by hbm2java
 */
@Embeddable
public class FriendRequestId  implements java.io.Serializable {


     private int senderId;
     private int receiverId;

    public FriendRequestId() {
    }

    public FriendRequestId(int senderId, int receiverId) {
       this.senderId = senderId;
       this.receiverId = receiverId;
    }
   


    @Column(name="SenderId", nullable=false)
    public int getSenderId() {
        return this.senderId;
    }
    
    public void setSenderId(int senderId) {
        this.senderId = senderId;
    }


    @Column(name="ReceiverId", nullable=false)
    public int getReceiverId() {
        return this.receiverId;
    }
    
    public void setReceiverId(int receiverId) {
        this.receiverId = receiverId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendRequestId) ) return false;
		 FriendRequestId castOther = ( FriendRequestId ) other; 
         
		 return (this.getSenderId()==castOther.getSenderId())
 && (this.getReceiverId()==castOther.getReceiverId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSenderId();
         result = 37 * result + this.getReceiverId();
         return result;
   }   


}


