package org.com.myapp.model;
// Generated Dec 4, 2014 12:47:13 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membership generated by hbm2java
 */
@Entity
@Table(name="membership"
    ,catalog="diary_v2"
)
public class Membership  implements java.io.Serializable {


     private int idmembership;
     private Date createdate;
     private String confirmationToken;
     private Boolean isConfirmed;
     private Date lastPasswordFailureDate;
     private Integer passwordFailuresSinceLastSuccess;
     private Date passwordChangedDate;
     private String passwordVerificationToken;
     private Date passwordVerificationTokenExpirationDate;

    public Membership() {
    }

	
    public Membership(int idmembership) {
        this.idmembership = idmembership;
    }
    public Membership(int idmembership, Date createdate, String confirmationToken, Boolean isConfirmed, Date lastPasswordFailureDate, Integer passwordFailuresSinceLastSuccess, Date passwordChangedDate, String passwordVerificationToken, Date passwordVerificationTokenExpirationDate) {
       this.idmembership = idmembership;
       this.createdate = createdate;
       this.confirmationToken = confirmationToken;
       this.isConfirmed = isConfirmed;
       this.lastPasswordFailureDate = lastPasswordFailureDate;
       this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
       this.passwordChangedDate = passwordChangedDate;
       this.passwordVerificationToken = passwordVerificationToken;
       this.passwordVerificationTokenExpirationDate = passwordVerificationTokenExpirationDate;
    }
   
     @Id 

    
    @Column(name="idmembership", unique=true, nullable=false)
    public int getIdmembership() {
        return this.idmembership;
    }
    
    public void setIdmembership(int idmembership) {
        this.idmembership = idmembership;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate", length=19)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    
    @Column(name="confirmationToken", length=125)
    public String getConfirmationToken() {
        return this.confirmationToken;
    }
    
    public void setConfirmationToken(String confirmationToken) {
        this.confirmationToken = confirmationToken;
    }

    
    @Column(name="IsConfirmed")
    public Boolean getIsConfirmed() {
        return this.isConfirmed;
    }
    
    public void setIsConfirmed(Boolean isConfirmed) {
        this.isConfirmed = isConfirmed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastPasswordFailureDate", length=19)
    public Date getLastPasswordFailureDate() {
        return this.lastPasswordFailureDate;
    }
    
    public void setLastPasswordFailureDate(Date lastPasswordFailureDate) {
        this.lastPasswordFailureDate = lastPasswordFailureDate;
    }

    
    @Column(name="PasswordFailuresSinceLastSuccess")
    public Integer getPasswordFailuresSinceLastSuccess() {
        return this.passwordFailuresSinceLastSuccess;
    }
    
    public void setPasswordFailuresSinceLastSuccess(Integer passwordFailuresSinceLastSuccess) {
        this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordChangedDate", length=19)
    public Date getPasswordChangedDate() {
        return this.passwordChangedDate;
    }
    
    public void setPasswordChangedDate(Date passwordChangedDate) {
        this.passwordChangedDate = passwordChangedDate;
    }

    
    @Column(name="PasswordVerificationToken", length=125)
    public String getPasswordVerificationToken() {
        return this.passwordVerificationToken;
    }
    
    public void setPasswordVerificationToken(String passwordVerificationToken) {
        this.passwordVerificationToken = passwordVerificationToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordVerificationTokenExpirationDate", length=19)
    public Date getPasswordVerificationTokenExpirationDate() {
        return this.passwordVerificationTokenExpirationDate;
    }
    
    public void setPasswordVerificationTokenExpirationDate(Date passwordVerificationTokenExpirationDate) {
        this.passwordVerificationTokenExpirationDate = passwordVerificationTokenExpirationDate;
    }




}


